---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "server/**.js"
exclude_patterns:
- "server/spec/"
- "node_modules/"
- "coverage/"
- ".nyc_output/"
- "UI/"